#!/usr/bin/env python
from __future__ import annotations
import logging
import requests
import yaml
import logging.config as log_config
from utils import *
from devices.fmc import AdderFMC
from devices.netbox import AdderNetbox
from pprint import pprint
import argparse

# Logging config
with open("./log/log.conf", "r") as f:
    try:
        contents = yaml.safe_load(f)
    except yaml.YAMLError:
        raise
    log_config.dictConfig(contents)

# Logging enable
logger = logging.getLogger(__name__)


def parse_arguments() -> argparse.Namespace:
    """Here we parse all our arguments, get the values and return them so we can pass into the main func"""
    parser = argparse.ArgumentParser(
        description="Adds DIA IP addresses from Netbox into the Cisco Firewalls and SROS routers"
    )
    deploy_rollback_group = parser.add_mutually_exclusive_group()
    group_get_ips = parser.add_mutually_exclusive_group()

    parser.add_argument(
        "--target",
        type=str,
        help="The name of the object group you want to update. Defaults to 'Store-DIA-PROD'",
    )
    group_get_ips.add_argument(
        "--site",
        type=str,
        help="The five letter site code you are trying to deploy. Site must be built in netbox for this to work.",
    )
    group_get_ips.add_argument(
        "--ip",
        type=str,
        help="Use this to manually specify the IP addresses you are trying to apply to the firewalls. Separate with spaces. Doesn't mix with --site",
        nargs="+",
    )
    deploy_rollback_group.add_argument(
        "--deploy",
        help="Push pending changes from the FMC to the FTDs",
        action="store_true",
    )
    deploy_rollback_group.add_argument(
        "--rollback",
        help="Rolls back the most recent change made to the FTD's DIA object-group. Cannot mix with --deploy",
        action="store_true",
    )

    return parser.parse_args()


def populate_site(
    site_code: str, nb: AdderNetbox, fmc: AdderFMC, target: str = None
) -> None:
    """Wrapping up all the logic to get from invocation of the entire app to adding a whole site to the firewalls"""
    # First we do some input validation. Make sure that the argument passed to the function is a five-letter WFM site code.
    try:
        validate_site_code(site_code)
    except SiteCodeError as e:
        logger.error(f"Site code invalid: {e}")
        raise

    if target == None:
        target = "Store-DIA-PROD"

    if site_code == "tests":
        dia_ips = [
            "169.254.100.201",
            "169.254.100.202",
            "169.254.100.203",
            "169.254.100.204",
        ]
        logger.debug(f"Using test list of IPs: {dia_ips}")
    else:
        dia_ips = nb.get_dia_ip_addrs(site_code)

    new_objects = fmc.create_host_objects(dia_ips)

    if site_code == "tests":
        obj_group = fmc.get_netgroup_uuid("adder_test")
        logger.debug(f"UUID of object group {site_code}: {obj_group}")
    else:
        obj_group = fmc.get_netgroup_uuid(target)

    if obj_group is not None:
        fmc.update_object_group(obj_group, new_objects)
        pprint(f"These are the new objects added: {new_objects}")
    else:
        raise SomethingBroke(obj_group, message=f"Cannot find {target} object group.")


def deploy_fmc(fmc: AdderFMC) -> tuple[requests.Response, requests.Response]:
    """If the --deploy flag is set, we will attempt to deploy changes to the ORD and DFW FTDs."""
    dfw_response = fmc.deploy_to_device(fmc.dfw_ftd)
    ord_response = fmc.deploy_to_device(fmc.ord_ftd)
    return (dfw_response, ord_response)


def populate_from_single(fmc: AdderFMC, new_ips: list, target: str = None) -> None:
    """Skip the netbox! This lets you enter a list of IPs into adder and have them added to the FMC"""
    # Determine what obj group we're going to modify
    if target is None:
        target = "Store-DIA-PROD"

    # Get UUID for object group to be modified
    obj_group = fmc.get_netgroup_uuid(target)

    # Create the host objects for the new IPs
    try:
        new_objects = fmc.create_host_objects(new_ips)
    except HostAlreadyExistsWarning as e:
        logger.debug(
            f"Host already exists, skipping creation process and adding host to object group."
        )
        if obj_group is not None:
            for ip in new_ips:
                fmc.update_group_from_existing_host(obj_group, ip)
    else:
        # Modify!
        if obj_group is not None:
            fmc.update_object_group(obj_group, new_objects)
        else:
            raise SomethingBroke(
                obj_group, message=f"Cannot find {target} object group."
            )


def rollback_fmc(fmc: AdderFMC) -> None:
    print("MOCK FUNC: rollback_fmc()")


def main(args):
    # Establish API connection object to FMC
    fmc = AdderFMC()

    # Establish API connection object to Netbox
    nb = AdderNetbox()

    deployable_devices = fmc.get_deployable_devices()
    for device in deployable_devices.json()["items"]:
        if device["name"] == fmc.ord_ftd:
            input(
                "The ORD FTD already has pending changes. ENTER to proceed, Ctrl-C to exit."
            )
            break

    for device in deployable_devices.json()["items"]:
        if device["name"] == fmc.dfw_ftd:
            input(
                "The DFW FTD already has pending changes. ENTER to proceed, Ctrl-C to exit."
            )
            break

    if args.site is not None:
        if args.target is not None:
            populate_site(args.site, nb, fmc, target=args.target)
        else:
            populate_site(args.site, nb, fmc)
        if args.deploy:
            _, _ = deploy_fmc(fmc)
    elif args.ip is not None:
        populate_from_single(fmc, args.ip, target=args.target)
        if args.deploy:
            deploy_fmc(fmc)
    elif args.deploy:
        deploy_fmc(fmc)
    elif args.rollback:
        rollback_fmc(fmc)


if __name__ == "__main__":
    args = parse_arguments()
    main(args)